In [32]:
import pandas as pd
from IPython.display import display
import os

regions = ["Abruzzo","Basilicata","Calabria","Campania","EmiliaRomagna","FriuliVeneziaGiulia","Lazio","Liguria","Lombardia","Marche","Molise","Piemonte","Puglia","Sardegna","Sicilia","Toscana","TrentinoAltoAdige","Umbria","ValledAosta","Veneto"]

industria_alimentare = []
totale_industria = []
rifiuti_alimentari = []
totale_rifiuti = []

for region in regions:
    df = pd.read_csv(f"/content/drive/MyDrive/Thesis/Python codes/Waste Production per Region/{region}/table_1_{region}.csv")
    index_01 = df.index[df[df.columns[0]].str.contains("10, 11 - Industria alimentare e delle bevande")] # index_01 is a Pandas Index object that contains the index labels of rows where the first column contains the specified string
    index_02 = df.index[df[df.columns[0]].str.contains("Totale")]
    industria_alimentare.append(df.iloc[index_01[0]][3]) # df.iloc[index_01[0]] returns the list of objects present in the corresponding rows, df.iloc[index_01[0]][3] selects the value that I need, in this case the one in the 4th column
    totale_industria.append(df.iloc[index_02[0]][3])
    
    
    df = pd.read_csv(f"/content/drive/MyDrive/Thesis/Python codes/Waste Production per Region/{region}/table_2_{region}.csv")
    index_01 = df.index[df[df.columns[1]].str.contains("Rifiuti prodotti da agricoltura, orticoltura, acquacoltura, selvicoltura, caccia e pesca, trattamento e preparazione di alimenti")]
    index_02 = df.index[df[df.columns[0]].str.contains("Totale")]
    rifiuti_alimentari.append(df.iloc[index_01[0]][4])
    totale_rifiuti.append(df.iloc[index_02[0]][4])

    
df = pd.DataFrame()
df.insert(0, 'NOME_REG', regions)
df.insert(1, 'ATECO 10,11 [t]', industria_alimentare)
df.insert(2, 'Totale industria', totale_industria)
df['ATECO 10,11 [t]']= [s.replace(".", "") for s in df['ATECO 10,11 [t]'].astype(str)]
df['Totale industria']= [s.replace(".", "") for s in df['Totale industria'].astype(str)]
df['Peso industria'] = round(df['ATECO 10,11 [t]'].astype(int)/df['Totale industria'].astype(int)*100,2)


df1 = pd.DataFrame()
df1.insert(0, 'NOME_REG', regions)
df1.insert(1, 'EER 02 [t]', rifiuti_alimentari)
df1.insert(2, 'Totale rifiuti', totale_rifiuti)
df1['EER 02 [t]']= [s.replace(".", "") for s in df1['EER 02 [t]'].astype(str)]
df1['Totale rifiuti']= [s.replace(".", "") for s in df1['Totale rifiuti'].astype(str)]
df1['Peso rifiuti'] = round(df1['EER 02 [t]'].astype(int)/df1['Totale rifiuti'].astype(int)*100,2)

display(df,df1)

path_data_arranged = '/content/drive/MyDrive/Thesis/Python codes/Waste Production per Region'
df.to_csv(os.path.join(path_data_arranged, 'Food Waste per ATECO.csv'))
df1.to_csv(os.path.join(path_data_arranged, 'Food Waste per EER.csv'))

               NOME_REG ATECO 10,11 [t] Totale industria  Peso industria
0               Abruzzo          120290          2934286            4.10
1            Basilicata           31523          2314039            1.36
2              Calabria           58650          2212084            2.65
3              Campania          268370          8436752            3.18
4         EmiliaRomagna          450739         13832669            3.26
5   FriuliVeneziaGiulia           58372          4218735            1.38
6                 Lazio          150106         10164452            1.48
7               Liguria           65361          2834408            2.31
8             Lombardia          583028         33540168            1.74
9                Marche           82223          3743696            2.20
10               Molise            1783           601719            0.30
11             Piemonte          303313         11896872            2.55
12               Puglia          204122         11388162            1.79
13             Sardegna           68707          3070948            2.24
14              Sicilia          182281          7373307            2.47
15              Toscana          169661         10086823            1.68
16    TrentinoAltoAdige           89331          4686283            1.91
17               Umbria           61553          3001267            2.05
18          ValledAosta            7444           292639            2.54
19               Veneto          408277         17345015            2.35

               NOME_REG EER 02 [t] Totale rifiuti  Peso rifiuti
0               Abruzzo      82006        2934286          2.79
1            Basilicata      27974        2314039          1.21
2              Calabria      55619        2212084          2.51
3              Campania     233689        8436752          2.77
4         EmiliaRomagna     522467       13832669          3.78
5   FriuliVeneziaGiulia      51206        4218735          1.21
6                 Lazio     141860       10164452          1.40
7               Liguria      60285        2834408          2.13
8             Lombardia     492142       33540168          1.47
9                Marche      79563        3743696          2.13
10               Molise      16282         601719          2.71
11             Piemonte     242955       11896872          2.04
12               Puglia     205229       11388162          1.80
13             Sardegna      66003        3070948          2.15
14              Sicilia     185530        7373307          2.52
15              Toscana     147575       10086823          1.46
16    TrentinoAltoAdige     103159        4686283          2.20
17               Umbria      58999        3001267          1.97
18          ValledAosta       6741         292639          2.30
19               Veneto     336147       17345015          1.94

In [11]:
import pandas as pd
from IPython.display import display

regions = ["Abruzzo","Basilicata","Calabria","Campania","EmiliaRomagna","FriuliVeneziaGiulia","Lazio","Liguria","Lombardia","Marche","Molise","Piemonte","Puglia","Sardegna","Sicilia","Toscana","TrentinoAltoAdige","Umbria","ValledAosta","Veneto"]
counter = 0
for region in regions:
  for i in range(1,3):
    print(counter)
    # Load the table into a dataframe
    df1 = pd.read_csv(f"/content/drive/MyDrive/Thesis/Python codes/Waste Production per Region/{region}/table_{i}_{region}.csv")

    # Get the values in the first column and extract the numbers
    col1 = df1.iloc[:, 0].values
    numbers = []
    for val in col1:
        if "-" in val:
            split_val = val.split("-")[0]
            if "," in split_val:
                split_val = split_val.split(",")[0]
        else:
          if "Totale" in val:
            continue
          split_val = val 
        if "ND" in split_val:
                continue       
        try:
            numbers.append(split_val.zfill(2))
        except ValueError:
            pass
    numbers = [s.replace(" ", "") for s in numbers] # remove spaces from the numbers

    numbers_temp = []
    for number in numbers:
      numbers_temp.append(int(number))

    # Find the missing values in the progression
    missing = []
    for i in range(1, max(numbers_temp) + 1):
        if str(i).zfill(2) not in numbers:
            missing.append(str(i).zfill(2))

    # Create a dataframe with the missing values and default values for the other columns
    missing_df = pd.DataFrame({df1.columns[0]: [str(i) + " missing" for i in missing],
                              df1.columns[1]: [None for i in range(len(missing))]})

    # Concatenate the original dataframe with the missing values dataframe
    df = pd.concat([df1, missing_df], sort=False)

    # Sort the dataframe based on the values in the first column
    df.sort_values(by=df.columns[0], inplace=True)

    # Reset the index of the dataframe
    df.reset_index(drop=True, inplace=True)

    # Save the dataframe to a csv file
    #df.to_csv("table_filled.csv", index=False)
    counter += 1
    display(df)

0

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,8.041,183,8.224
1,02 missing,None,NaN,NaN
2,03 - Pesca e acquacoltura,12,-,12
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,"93 - Attività sportive, di intrattenimento e d...",104,-,104
93,94 - Attività di organizzazioni associative,1,1,2
94,95 - Riparazione di computer e di beni per uso...,20,3,23
95,96 - Altre attività di servizi per la persona,1.267,315,1.582
96,Totale,2.833.816,100.470,2.934.286

1

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",5.959,140,6.099
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",82.000,6,82.006
2,03,Rifiuti della lavorazione del legno e della pr...,52.541,214,52.755
3,04,Rifiuti della lavorazione di pelli e pellicce ...,4.740,-,4.740
4,05,"Rifiuti della raffinazione del petrolio, purif...",-,518,518
5,06,Rifiuti dei processi chimici inorganici,3.065,3.995,7.060
6,07,Rifiuti dei processi chimici organici,9.194,3.838,13.032
7,08,"Rifiuti della produzione, formulazione, fornit...",9.270,1.728,10.998
8,09,Rifiuti dell'industria fotografica,24,99,123
9,10,Rifiuti provenienti da processi termici,33.371,2.295,35.666
10,11,Rifiuti prodotti dal trattamento chimico super...,3.650,5.802,9.452
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,154.206,3.482,157.688
12,13,Oli esauriti e residui di combustibili liquidi...,-,5.150,5.150
13,14,"Solventi organici, refrigeranti e propellenti ...",-,827,827
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",79.357,3.102,82.459
15,16,Rifiuti non specificati altrimenti nell'elenco,141.060,45.060,186.120
16,17,Rifiuti delle attività di costruzione e demoli...,1.498.560,7.240,1.505.800
17,18,Rifiuti prodotti dal settore sanitario e veter...,305,3.618,3.923
18,19,Rifiuti prodotti da impianti di gestione dei r...,723.356,13.097,736.453
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,33.158,259,33.417
20,Totale,Totale,2.833.816,100.470,2.934.286

2

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,1.293,63,1.356
1,02 - Silvicoltura ed utilizzo di aree forestali,-,2,2
2,03 missing,None,NaN,NaN
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,93 missing,None,NaN,NaN
93,94 - Attività di organizzazioni associative,23,-,23
94,95 missing,None,NaN,NaN
95,96 - Altre attività di servizi per la persona,237,6,243
96,Totale,2.176.201,137.838,2.314.039

3

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",4.519,174,4.693
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",27.972,2,27.974
2,03,Rifiuti della lavorazione del legno e della pr...,3.763,43,3.806
3,04,Rifiuti della lavorazione di pelli e pellicce ...,1.901,-,1.901
4,05,"Rifiuti della raffinazione del petrolio, purif...",-,670,670
5,06,Rifiuti dei processi chimici inorganici,90,93,183
6,07,Rifiuti dei processi chimici organici,4.865,1.033,5.898
7,08,"Rifiuti della produzione, formulazione, fornit...",715,464,1.179
8,09,Rifiuti dell'industria fotografica,4,18,22
9,10,Rifiuti provenienti da processi termici,10.961,12.039,23.000
10,11,Rifiuti prodotti dal trattamento chimico super...,134,684,818
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,51.934,1.114,53.048
12,13,Oli esauriti e residui di combustibili liquidi...,-,31.929,31.929
13,14,"Solventi organici, refrigeranti e propellenti ...",-,138,138
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",24.568,2.964,27.532
15,16,Rifiuti non specificati altrimenti nell'elenco,1.052.562,51.079,1.103.641
16,17,Rifiuti delle attività di costruzione e demoli...,701.928,3.090,705.018
17,18,Rifiuti prodotti dal settore sanitario e veter...,53,1.168,1.221
18,19,Rifiuti prodotti da impianti di gestione dei r...,281.411,31.087,312.498
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,8.821,49,8.870
20,Totale,Totale,2.176.201,137.838,2.314.039

4

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,1.038,133,1.171
1,02 missing,None,NaN,NaN
2,03 missing,None,NaN,NaN
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
93,94 missing,None,NaN,NaN
94,95 missing,None,NaN,NaN
95,96 - Altre attività di servizi per la persona,120,18,138
96,ND - Attività ISTAT non determinata,4,-,4
97,Totale,2.030.231,181.853,2.212.084

5

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",5.682,-,5.682
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",55.619,-,55.619
2,03,Rifiuti della lavorazione del legno e della pr...,2.375,10,2.385
3,04,Rifiuti della lavorazione di pelli e pellicce ...,636,-,636
4,05,"Rifiuti della raffinazione del petrolio, purif...",-,114,114
5,06,Rifiuti dei processi chimici inorganici,8.775,13,8.788
6,07,Rifiuti dei processi chimici organici,702,75,777
7,08,"Rifiuti della produzione, formulazione, fornit...",735,105,840
8,09,Rifiuti dell'industria fotografica,10,27,37
9,10,Rifiuti provenienti da processi termici,49.943,4.349,54.292
10,11,Rifiuti prodotti dal trattamento chimico super...,871,14,885
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,11.283,558,11.841
12,13,Oli esauriti e residui di combustibili liquidi...,-,5.096,5.096
13,14,"Solventi organici, refrigeranti e propellenti ...",-,11,11
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",20.731,887,21.618
15,16,Rifiuti non specificati altrimenti nell'elenco,134.890,47.643,182.533
16,17,Rifiuti delle attività di costruzione e demoli...,691.057,8.276,699.333
17,18,Rifiuti prodotti dal settore sanitario e veter...,503,2.188,2.691
18,19,Rifiuti prodotti da impianti di gestione dei r...,1.032.414,110.958,1.143.372
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,14.001,1.529,15.530
20,ND,Attività ISTAT non determinata,4,-,4
21,Totale,Totale,2.030.231,181.853,2.212.084

6

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,11.510,331,11.841
1,02 missing,None,NaN,NaN
2,03 - Pesca e acquacoltura,127,6,133
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
96,97 missing,None,NaN,NaN
97,98 - Produzione di beni e servizi indifferenzi...,1,-,1
98,99 - Organizzazioni ed organismi extraterritor...,115,5,120
99,ND - Attività ISTAT non determinata,1.027,98,1.125
100,Totale,8.055.563,381.189,8.436.752

7

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",5.422,-,5.422
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",233.687,2,233.689
2,03,Rifiuti della lavorazione del legno e della pr...,32.918,462,33.380
3,04,Rifiuti della lavorazione di pelli e pellicce ...,39.864,25,39.889
4,05,"Rifiuti della raffinazione del petrolio, purif...",-,1.193,1.193
5,06,Rifiuti dei processi chimici inorganici,1.472,4.945,6.417
6,07,Rifiuti dei processi chimici organici,13.522,4.704,18.226
7,08,"Rifiuti della produzione, formulazione, fornit...",11.085,6.490,17.575
8,09,Rifiuti dell'industria fotografica,232,389,621
9,10,Rifiuti provenienti da processi termici,41.227,12.466,53.693
10,11,Rifiuti prodotti dal trattamento chimico super...,4.901,8.018,12.919
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,141.302,6.031,147.333
12,13,Oli esauriti e residui di combustibili liquidi...,-,33.609,33.609
13,14,"Solventi organici, refrigeranti e propellenti ...",-,785,785
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",254.030,8.867,262.897
15,16,Rifiuti non specificati altrimenti nell'elenco,322.506,171.049,493.555
16,17,Rifiuti delle attività di costruzione e demoli...,4.077.754,29.571,4.107.325
17,18,Rifiuti prodotti dal settore sanitario e veter...,1.418,13.575,14.993
18,19,Rifiuti prodotti da impianti di gestione dei r...,2.778.986,78.395,2.857.381
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,94.210,515,94.725
20,ND,Attività ISTAT non determinata,1.027,98,1.125
21,Totale,Totale,8.055.563,381.189,8.436.752

8

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,133.065,1.005,134.070
1,02 - Silvicoltura ed utilizzo di aree forestali,722,-,722
2,03 - Pesca e acquacoltura,144,5,149
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,"93 - Attività sportive, di intrattenimento e d...",1.672,218,1.890
93,94 - Attività di organizzazioni associative,1.003,33,1.036
94,95 - Riparazione di computer e di beni per uso...,72,22,94
95,96 - Altre attività di servizi per la persona,2.518,3.588,6.106
96,Totale,12.856.186,976.483,13.832.669

9

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",33.497,717,34.214
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",522.429,38,522.467
2,03,Rifiuti della lavorazione del legno e della pr...,119.932,1.322,121.254
3,04,Rifiuti della lavorazione di pelli e pellicce ...,12.871,-,12.871
4,05,"Rifiuti della raffinazione del petrolio, purif...",4,3.120,3.124
5,06,Rifiuti dei processi chimici inorganici,6.870,8.724,15.594
6,07,Rifiuti dei processi chimici organici,47.665,106.486,154.151
7,08,"Rifiuti della produzione, formulazione, fornit...",498.565,10.581,509.146
8,09,Rifiuti dell'industria fotografica,175,1.456,1.631
9,10,Rifiuti provenienti da processi termici,640.297,12.840,653.137
10,11,Rifiuti prodotti dal trattamento chimico super...,23.795,15.187,38.982
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,742.522,85.948,828.470
12,13,Oli esauriti e residui di combustibili liquidi...,-,73.280,73.280
13,14,"Solventi organici, refrigeranti e propellenti ...",-,10.813,10.813
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",516.555,20.511,537.066
15,16,Rifiuti non specificati altrimenti nell'elenco,534.748,197.365,732.113
16,17,Rifiuti delle attività di costruzione e demoli...,5.274.254,67.986,5.342.240
17,18,Rifiuti prodotti dal settore sanitario e veter...,5.391,14.464,19.855
18,19,Rifiuti prodotti da impianti di gestione dei r...,3.461.714,344.267,3.805.981
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,414.902,1.378,416.280
20,Totale,Totale,12.856.186,976.483,13.832.669

10

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,1.850,297,2.147
1,02 - Silvicoltura ed utilizzo di aree forestali,10,6,16
2,03 - Pesca e acquacoltura,29,4,33
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
95,96 - Altre attività di servizi per la persona,302,48,350
96,97 missing,None,NaN,NaN
97,98 - Produzione di beni e servizi indifferenzi...,9,2,11
98,ND - Attività ISTAT non determinata,-,4,4
99,Totale,3.948.862,269.873,4.218.735

11

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",14.815,-,14.815
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",51.194,12,51.206
2,03,Rifiuti della lavorazione del legno e della pr...,259.425,131,259.556
3,04,Rifiuti della lavorazione di pelli e pellicce ...,5.592,48,5.640
4,05,"Rifiuti della raffinazione del petrolio, purif...",-,47,47
5,06,Rifiuti dei processi chimici inorganici,3.939,4.802,8.741
6,07,Rifiuti dei processi chimici organici,11.373,21.359,32.732
7,08,"Rifiuti della produzione, formulazione, fornit...",12.983,4.360,17.343
8,09,Rifiuti dell'industria fotografica,38,1.079,1.117
9,10,Rifiuti provenienti da processi termici,231.932,63.582,295.514
10,11,Rifiuti prodotti dal trattamento chimico super...,8.454,16.074,24.528
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,272.716,13.956,286.672
12,13,Oli esauriti e residui di combustibili liquidi...,-,44.456,44.456
13,14,"Solventi organici, refrigeranti e propellenti ...",-,1.201,1.201
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",110.451,5.952,116.403
15,16,Rifiuti non specificati altrimenti nell'elenco,119.054,44.955,164.009
16,17,Rifiuti delle attività di costruzione e demoli...,1.878.017,12.706,1.890.723
17,18,Rifiuti prodotti dal settore sanitario e veter...,144,5.195,5.339
18,19,Rifiuti prodotti da impianti di gestione dei r...,902.710,29.894,932.604
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,66.025,60,66.085
20,ND,Attività ISTAT non determinata,-,4,4
21,Totale,Totale,3.948.862,269.873,4.218.735

12

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,6.144,227,6.371
1,02 - Silvicoltura ed utilizzo di aree forestali,28,1,29
2,03 - Pesca e acquacoltura,30,8,38
3,04 missing,None,NaN,NaN
4,05 - Estrazione di carbone (esclusa torba),6,3,9
...,...,...,...,...
96,97 missing,None,NaN,NaN
97,98 - Produzione di beni e servizi indifferenzi...,2,-,2
98,99 - Organizzazioni ed organismi extraterritor...,108,30,138
99,ND - Attività ISTAT non determinata,26,4,30
100,Totale,9.651.114,513.338,10.164.452

13

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",409.827,532.000,410.359
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",141.853,7.000,141.860
2,03,Rifiuti della lavorazione del legno e della pr...,76.356,518.000,76.874
3,04,Rifiuti della lavorazione di pelli e pellicce ...,3.865,12.000,3.877
4,05,"Rifiuti della raffinazione del petrolio, purif...",2,250.000,252
5,06,Rifiuti dei processi chimici inorganici,5.854,2.564,8.418
6,07,Rifiuti dei processi chimici organici,17.338,42.361,59.699
7,08,"Rifiuti della produzione, formulazione, fornit...",16.514,2.417,18.931
8,09,Rifiuti dell'industria fotografica,88,1.016,1.104
9,10,Rifiuti provenienti da processi termici,309.305,8.401,317.706
10,11,Rifiuti prodotti dal trattamento chimico super...,2.093,2.989,5.082
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,52.038,2.971,55.009
12,13,Oli esauriti e residui di combustibili liquidi...,-,59.184,59.184
13,14,"Solventi organici, refrigeranti e propellenti ...",-,676.000,676
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",207.317,9.878,217.195
15,16,Rifiuti non specificati altrimenti nell'elenco,392.804,166.086,558.890
16,17,Rifiuti delle attività di costruzione e demoli...,4.686.154,24.322,4.710.476
17,18,Rifiuti prodotti dal settore sanitario e veter...,2.029,24.170,26.199
18,19,Rifiuti prodotti da impianti di gestione dei r...,3.107.586,164.251,3.271.837
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,220.065,729.000,220.794
20,ND,Attività ISTAT non determinata,26,4.000,30
21,Totale,Totale,9.651.114,513.338,10.164.452

14

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,105,101,206
1,02 missing,None,NaN,NaN
2,03 - Pesca e acquacoltura,1,1,2
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,"93 - Attività sportive, di intrattenimento e d...",52,24,76
93,94 - Attività di organizzazioni associative,13,3,16
94,95 - Riparazione di computer e di beni per uso...,24,4,28
95,96 - Altre attività di servizi per la persona,461,57,518
96,Totale,2.649.477,184.931,2.834.408

15

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",33.829,-,33.829
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",60.285,-,60.285
2,03,Rifiuti della lavorazione del legno e della pr...,2.555,178,2.733
3,04,Rifiuti della lavorazione di pelli e pellicce ...,701,-,701
4,05,"Rifiuti della raffinazione del petrolio, purif...",78,899,977
5,06,Rifiuti dei processi chimici inorganici,2.573,2.154,4.727
6,07,Rifiuti dei processi chimici organici,4.719,8.318,13.037
7,08,"Rifiuti della produzione, formulazione, fornit...",951,889,1.840
8,09,Rifiuti dell'industria fotografica,10,138,148
9,10,Rifiuti provenienti da processi termici,76.505,1.322,77.827
10,11,Rifiuti prodotti dal trattamento chimico super...,613,2.547,3.160
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,28.533,10.761,39.294
12,13,Oli esauriti e residui di combustibili liquidi...,-,62.170,62.170
13,14,"Solventi organici, refrigeranti e propellenti ...",-,170,170
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",39.717,4.396,44.113
15,16,Rifiuti non specificati altrimenti nell'elenco,127.183,55.805,182.988
16,17,Rifiuti delle attività di costruzione e demoli...,1.403.662,25.656,1.429.318
17,18,Rifiuti prodotti dal settore sanitario e veter...,119,4.772,4.891
18,19,Rifiuti prodotti da impianti di gestione dei r...,820.152,4.656,824.808
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,47.292,100,47.392
20,Totale,Totale,2.649.477,184.931,2.834.408

16

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,55.116,1.969,57.085
1,02 - Silvicoltura ed utilizzo di aree forestali,2.711,8,2.719
2,03 - Pesca e acquacoltura,37,-,37
3,04 missing,None,NaN,NaN
4,05 - Estrazione di carbone (esclusa torba),-,2,2
...,...,...,...,...
94,95 - Riparazione di computer e di beni per uso...,2.042,159,2.201
95,96 - Altre attività di servizi per la persona,3.779,3.349,7.128
96,97 - Attività di famiglie e convivenze come da...,25,-,25
97,98 - Produzione di beni e servizi indifferenzi...,161,-,161
98,Totale,30.408.037,3.132.131,33.540.168

17

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",88.026,110,88.136
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",492.107,35,492.142
2,03,Rifiuti della lavorazione del legno e della pr...,410.791,619,411.410
3,04,Rifiuti della lavorazione di pelli e pellicce ...,69.002,319,69.321
4,05,"Rifiuti della raffinazione del petrolio, purif...",355,15.743,16.098
5,06,Rifiuti dei processi chimici inorganici,55.201,48.874,104.075
6,07,Rifiuti dei processi chimici organici,149.716,611.307,761.023
7,08,"Rifiuti della produzione, formulazione, fornit...",105.284,21.957,127.241
8,09,Rifiuti dell'industria fotografica,351,2.778,3.129
9,10,Rifiuti provenienti da processi termici,2.209.958,261.054,2.471.012
10,11,Rifiuti prodotti dal trattamento chimico super...,57.275,116.116,173.391
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,1.566.718,155.758,1.722.476
12,13,Oli esauriti e residui di combustibili liquidi...,-,365.135,365.135
13,14,"Solventi organici, refrigeranti e propellenti ...",-,14.887,14.887
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",1.161.342,54.086,1.215.428
15,16,Rifiuti non specificati altrimenti nell'elenco,819.044,461.759,1.280.803
16,17,Rifiuti delle attività di costruzione e demoli...,14.617.152,168.839,14.785.991
17,18,Rifiuti prodotti dal settore sanitario e veter...,7.906,32.008,39.914
18,19,Rifiuti prodotti da impianti di gestione dei r...,8.032.065,796.322,8.828.387
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,565.744,4.425,570.169
20,Totale,Totale,30.408.037,3.132.131,33.540.168

18

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,8.290,181,8.471
1,02 missing,None,NaN,NaN
2,03 - Pesca e acquacoltura,146,875,1.021
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
96,97 missing,None,NaN,NaN
97,98 missing,None,NaN,NaN
98,99 - Organizzazioni ed organismi extraterritor...,4,1,5
99,ND - Attività ISTAT non determinata,84,6,90
100,Totale,3.576.086,167.610,3.743.696

19

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",14.636,-,14.636
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",79.561,2,79.563
2,03,Rifiuti della lavorazione del legno e della pr...,181.982,305,182.287
3,04,Rifiuti della lavorazione di pelli e pellicce ...,31.765,-,31.765
4,05,"Rifiuti della raffinazione del petrolio, purif...",11.645,1.240,12.885
5,06,Rifiuti dei processi chimici inorganici,3.969,3.709,7.678
6,07,Rifiuti dei processi chimici organici,19.453,4.634,24.087
7,08,"Rifiuti della produzione, formulazione, fornit...",23.296,2.592,25.888
8,09,Rifiuti dell'industria fotografica,25,189,214
9,10,Rifiuti provenienti da processi termici,57.290,1.293,58.583
10,11,Rifiuti prodotti dal trattamento chimico super...,6.042,7.624,13.666
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,143.526,4.737,148.263
12,13,Oli esauriti e residui di combustibili liquidi...,-,19.454,19.454
13,14,"Solventi organici, refrigeranti e propellenti ...",-,2.495,2.495
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",117.210,4.037,121.247
15,16,Rifiuti non specificati altrimenti nell'elenco,117.192,60.770,177.962
16,17,Rifiuti delle attività di costruzione e demoli...,1.768.384,7.608,1.775.992
17,18,Rifiuti prodotti dal settore sanitario e veter...,2.613,3.960,6.573
18,19,Rifiuti prodotti da impianti di gestione dei r...,956.264,42.792,999.056
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,41.149,163,41.312
20,ND,Attività ISTAT non determinata,84,6,90
21,Totale,Totale,3.576.086,167.610,3.743.696

20

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,71,69,140.000
1,02 missing,None,NaN,NaN
2,03 missing,None,NaN,NaN
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,93 missing,None,NaN,NaN
93,94 missing,None,NaN,NaN
94,95 missing,None,NaN,NaN
95,96 - Altre attività di servizi per la persona,146,6,152.000
96,Totale,559.860,41.859,601.719

21

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",120,-,120.000
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",16.282,-,16.282
2,03,Rifiuti della lavorazione del legno e della pr...,462,152,614.000
3,04,Rifiuti della lavorazione di pelli e pellicce ...,334,-,334.000
4,05,"Rifiuti della raffinazione del petrolio, purif...",-,32,32.000
5,06,Rifiuti dei processi chimici inorganici,40,4.432,4.472
6,07,Rifiuti dei processi chimici organici,3.518,18.138,21.656
7,08,"Rifiuti della produzione, formulazione, fornit...",261,151,412.000
8,09,Rifiuti dell'industria fotografica,21,2,23.000
9,10,Rifiuti provenienti da processi termici,12.794,-,12.794
10,11,Rifiuti prodotti dal trattamento chimico super...,110,85,195.000
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,14.874,488,15.362
12,13,Oli esauriti e residui di combustibili liquidi...,-,1.118,1.118
13,14,"Solventi organici, refrigeranti e propellenti ...",-,48,48.000
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",14.192,1.208,15.400
15,16,Rifiuti non specificati altrimenti nell'elenco,17.390,10.153,27.543
16,17,Rifiuti delle attività di costruzione e demoli...,293.475,562,294.037
17,18,Rifiuti prodotti dal settore sanitario e veter...,28,1.297,1.325
18,19,Rifiuti prodotti da impianti di gestione dei r...,183.091,3.766,186.857
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,2.868,227,3.095
20,Totale,Totale,559.860,41.859,601.719

22

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,7.151,584,7.735
1,02 - Silvicoltura ed utilizzo di aree forestali,66,5,71
2,03 - Pesca e acquacoltura,-,89,89
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
95,96 - Altre attività di servizi per la persona,636,184,820
96,97 missing,None,NaN,NaN
97,98 missing,None,NaN,NaN
98,99 - Organizzazioni ed organismi extraterritor...,5,2,7
99,Totale,10.805.220,1.091.652,11.896.872

23

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",57.894,-,57.894
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",242.943,12,242.955
2,03,Rifiuti della lavorazione del legno e della pr...,118.735,10.746,129.481
3,04,Rifiuti della lavorazione di pelli e pellicce ...,28.806,55,28.861
4,05,"Rifiuti della raffinazione del petrolio, purif...",1.002,1.988,2.990
5,06,Rifiuti dei processi chimici inorganici,128.835,5.992,134.827
6,07,Rifiuti dei processi chimici organici,52.559,88.412,140.971
7,08,"Rifiuti della produzione, formulazione, fornit...",20.950,10.241,31.191
8,09,Rifiuti dell'industria fotografica,44,888,932
9,10,Rifiuti provenienti da processi termici,184.399,42.458,226.857
10,11,Rifiuti prodotti dal trattamento chimico super...,12.760,23.548,36.308
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,645.789,91.958,737.747
12,13,Oli esauriti e residui di combustibili liquidi...,-,55.422,55.422
13,14,"Solventi organici, refrigeranti e propellenti ...",-,8.430,8.430
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",411.742,28.254,439.996
15,16,Rifiuti non specificati altrimenti nell'elenco,372.762,209.074,581.836
16,17,Rifiuti delle attività di costruzione e demoli...,5.987.254,154.041,6.141.295
17,18,Rifiuti prodotti dal settore sanitario e veter...,223,11.633,11.856
18,19,Rifiuti prodotti da impianti di gestione dei r...,2.374.517,347.132,2.721.649
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,164.006,1.368,165.374
20,Totale,Totale,10.805.220,1.091.652,11.896.872

24

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,9.922,342,10.264
1,02 missing,None,NaN,NaN
2,03 - Pesca e acquacoltura,32,6,38
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
96,97 missing,None,NaN,NaN
97,98 - Produzione di beni e servizi indifferenzi...,1,-,1
98,99 - Organizzazioni ed organismi extraterritor...,143,16,159
99,ND - Attività ISTAT non determinata,-,1,1
100,Totale,11.001.478,386.684,11.388.162

25

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",29.636,16,29.652
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",205.227,2,205.229
2,03,Rifiuti della lavorazione del legno e della pr...,61.328,308,61.636
3,04,Rifiuti della lavorazione di pelli e pellicce ...,13.378,-,13.378
4,05,"Rifiuti della raffinazione del petrolio, purif...",7,1.357,1.364
5,06,Rifiuti dei processi chimici inorganici,3.712,2.301,6.013
6,07,Rifiuti dei processi chimici organici,19.315,6.240,25.555
7,08,"Rifiuti della produzione, formulazione, fornit...",4.394,1.458,5.852
8,09,Rifiuti dell'industria fotografica,34,440,474
9,10,Rifiuti provenienti da processi termici,2.845.559,13.813,2.859.372
10,11,Rifiuti prodotti dal trattamento chimico super...,2.269,2.135,4.404
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,49.684,9.981,59.665
12,13,Oli esauriti e residui di combustibili liquidi...,-,52.386,52.386
13,14,"Solventi organici, refrigeranti e propellenti ...",-,253,253
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",100.169,5.102,105.271
15,16,Rifiuti non specificati altrimenti nell'elenco,556.645,201.261,757.906
16,17,Rifiuti delle attività di costruzione e demoli...,4.340.607,25.676,4.366.283
17,18,Rifiuti prodotti dal settore sanitario e veter...,488,14.202,14.690
18,19,Rifiuti prodotti da impianti di gestione dei r...,2.560.477,49.649,2.610.126
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,208.549,103,208.652
20,ND,Attività ISTAT non determinata,-,1,1
21,Totale,Totale,11.001.478,386.684,11.388.162

26

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,564,64,628
1,02 - Silvicoltura ed utilizzo di aree forestali,-,1,1
2,03 - Pesca e acquacoltura,1.049,1,1.050
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,"93 - Attività sportive, di intrattenimento e d...",89,9,98
93,94 - Attività di organizzazioni associative,24,35,59
94,95 - Riparazione di computer e di beni per uso...,-,17,17
95,96 - Altre attività di servizi per la persona,234,62,296
96,Totale,2.730.669,340.279,3.070.948

27

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",298,182,480
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",65.999,4,66.003
2,03,Rifiuti della lavorazione del legno e della pr...,4.154,120,4.274
3,04,Rifiuti della lavorazione di pelli e pellicce ...,522,-,522
4,05,"Rifiuti della raffinazione del petrolio, purif...",252,39.008,39.260
5,06,Rifiuti dei processi chimici inorganici,838,1.982,2.820
6,07,Rifiuti dei processi chimici organici,1.828,1.824,3.652
7,08,"Rifiuti della produzione, formulazione, fornit...",810,277,1.087
8,09,Rifiuti dell'industria fotografica,38,49,87
9,10,Rifiuti provenienti da processi termici,442.269,45.581,487.850
10,11,Rifiuti prodotti dal trattamento chimico super...,2.219,70.013,72.232
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,7.281,981,8.262
12,13,Oli esauriti e residui di combustibili liquidi...,-,6.961,6.961
13,14,"Solventi organici, refrigeranti e propellenti ...",-,102,102
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",16.324,3.837,20.161
15,16,Rifiuti non specificati altrimenti nell'elenco,104.680,58.704,163.384
16,17,Rifiuti delle attività di costruzione e demoli...,1.372.268,44.786,1.417.054
17,18,Rifiuti prodotti dal settore sanitario e veter...,97,4.974,5.071
18,19,Rifiuti prodotti da impianti di gestione dei r...,654.352,60.677,715.029
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,56.440,217,56.657
20,Totale,Totale,2.730.669,340.279,3.070.948

28

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,6.378,409,6.787
1,02 - Silvicoltura ed utilizzo di aree forestali,57,10,67
2,03 - Pesca e acquacoltura,2,58,60
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
93,94 - Attività di organizzazioni associative,88,7,95
94,95 - Riparazione di computer e di beni per uso...,8,2,10
95,96 - Altre attività di servizi per la persona,1.089,59,1.148
96,ND - Attività ISTAT non determinata,9,7,16
97,Totale,7.046.198,327.109,7.373.307

29

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",48.036,1.214,49.250
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",185.530,-,185.530
2,03,Rifiuti della lavorazione del legno e della pr...,6.233,363,6.596
3,04,Rifiuti della lavorazione di pelli e pellicce ...,1.294,-,1.294
4,05,"Rifiuti della raffinazione del petrolio, purif...",1.159,12.551,13.710
5,06,Rifiuti dei processi chimici inorganici,457,22.057,22.514
6,07,Rifiuti dei processi chimici organici,3.421,5.917,9.338
7,08,"Rifiuti della produzione, formulazione, fornit...",2.844,1.129,3.973
8,09,Rifiuti dell'industria fotografica,49,446,495
9,10,Rifiuti provenienti da processi termici,48.453,8.476,56.929
10,11,Rifiuti prodotti dal trattamento chimico super...,2.024,901,2.925
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,16.992,2.953,19.945
12,13,Oli esauriti e residui di combustibili liquidi...,-,24.490,24.490
13,14,"Solventi organici, refrigeranti e propellenti ...",-,636,636
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",63.919,3.504,67.423
15,16,Rifiuti non specificati altrimenti nell'elenco,249.135,157.951,407.086
16,17,Rifiuti delle attività di costruzione e demoli...,3.806.653,21.908,3.828.561
17,18,Rifiuti prodotti dal settore sanitario e veter...,676,9.595,10.271
18,19,Rifiuti prodotti da impianti di gestione dei r...,2.566.674,52.000,2.618.674
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,42.640,1.011,43.651
20,ND,Attività ISTAT non determinata,9,7,16
21,Totale,Totale,7.046.198,327.109,7.373.307

30

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,4.946,581,5.527
1,02 - Silvicoltura ed utilizzo di aree forestali,260,60,320
2,03 - Pesca e acquacoltura,33,1,34
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
96,97 missing,None,NaN,NaN
97,98 missing,None,NaN,NaN
98,99 - Organizzazioni ed organismi extraterritor...,-,1,1
99,ND - Attività ISTAT non determinata,10,15,25
100,Totale,9.641.598,445.225,10.086.823

31

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",246.380,92.000,246.472
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",147.558,17.000,147.575
2,03,Rifiuti della lavorazione del legno e della pr...,264.846,202.000,265.048
3,04,Rifiuti della lavorazione di pelli e pellicce ...,202.139,171.000,202.310
4,05,"Rifiuti della raffinazione del petrolio, purif...",1.446,2.305,3.751
5,06,Rifiuti dei processi chimici inorganici,453.965,6.290,460.255
6,07,Rifiuti dei processi chimici organici,16.721,12.595,29.316
7,08,"Rifiuti della produzione, formulazione, fornit...",28.540,4.600,33.140
8,09,Rifiuti dell'industria fotografica,51,191.000,242
9,10,Rifiuti provenienti da processi termici,73.639,6.076,79.715
10,11,Rifiuti prodotti dal trattamento chimico super...,29.622,27.317,56.939
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,105.291,10.041,115.332
12,13,Oli esauriti e residui di combustibili liquidi...,-,41.925,41.925
13,14,"Solventi organici, refrigeranti e propellenti ...",-,2.740,2.740
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",244.510,20.852,265.362
15,16,Rifiuti non specificati altrimenti nell'elenco,263.988,120.297,384.285
16,17,Rifiuti delle attività di costruzione e demoli...,4.251.324,34.360,4.285.684
17,18,Rifiuti prodotti dal settore sanitario e veter...,1.791,10.400,12.191
18,19,Rifiuti prodotti da impianti di gestione dei r...,3.156.160,143.594,3.299.754
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,153.617,1.145,154.762
20,ND,Attività ISTAT non determinata,10,15.000,25
21,Totale,Totale,9.641.598,445.225,10.086.823

32

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,16.090,424,16.514
1,02 - Silvicoltura ed utilizzo di aree forestali,367,9,376
2,03 missing,None,NaN,NaN
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,"93 - Attività sportive, di intrattenimento e d...",27,50,77
93,94 - Attività di organizzazioni associative,33,49,82
94,95 - Riparazione di computer e di beni per uso...,2,6,8
95,96 - Altre attività di servizi per la persona,209,31,240
96,Totale,4.577.364,108.919,4.686.283

33

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",91.192,-,91.192
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",103.146,13,103.159
2,03,Rifiuti della lavorazione del legno e della pr...,60.014,247,60.261
3,04,Rifiuti della lavorazione di pelli e pellicce ...,883,3,886
4,05 missing,None,NaN,NaN,NaN
5,06,Rifiuti dei processi chimici inorganici,897,2.787,3.684
6,07,Rifiuti dei processi chimici organici,13.275,10.615,23.890
7,08,"Rifiuti della produzione, formulazione, fornit...",2.689,2.123,4.812
8,09,Rifiuti dell'industria fotografica,7,857,864
9,10,Rifiuti provenienti da processi termici,99.525,7.900,107.425
10,11,Rifiuti prodotti dal trattamento chimico super...,1.502,3.328,4.830
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,57.459,9.779,67.238
12,13,Oli esauriti e residui di combustibili liquidi...,-,9.986,9.986
13,14,"Solventi organici, refrigeranti e propellenti ...",-,187,187
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",57.115,3.555,60.670
15,16,Rifiuti non specificati altrimenti nell'elenco,54.658,31.082,85.740
16,17,Rifiuti delle attività di costruzione e demoli...,3.125.814,11.193,3.137.007
17,18,Rifiuti prodotti dal settore sanitario e veter...,204,2.265,2.469
18,19,Rifiuti prodotti da impianti di gestione dei r...,856.149,12.051,868.200
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,52.835,948,53.783
20,Totale,Totale,4.577.364,108.919,4.686.283

34

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,5.910,180,6.090
1,02 - Silvicoltura ed utilizzo di aree forestali,194,5,199
2,03 missing,None,NaN,NaN
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,"93 - Attività sportive, di intrattenimento e d...",1,2,3
93,94 - Attività di organizzazioni associative,17,-,17
94,95 - Riparazione di computer e di beni per uso...,13,10,23
95,96 - Altre attività di servizi per la persona,1.287,43,1.330
96,Totale,2.840.177,161.090,3.001.267

35

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",34.663,14,34.677
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",58.992,7,58.999
2,03,Rifiuti della lavorazione del legno e della pr...,26.599,210,26.809
3,04,Rifiuti della lavorazione di pelli e pellicce ...,5.169,-,5.169
4,05,"Rifiuti della raffinazione del petrolio, purif...",-,145,145
5,06,Rifiuti dei processi chimici inorganici,1.208,423,1.631
6,07,Rifiuti dei processi chimici organici,12.861,3.244,16.105
7,08,"Rifiuti della produzione, formulazione, fornit...",4.213,880,5.093
8,09,Rifiuti dell'industria fotografica,11,133,144
9,10,Rifiuti provenienti da processi termici,359.983,13.536,373.519
10,11,Rifiuti prodotti dal trattamento chimico super...,1.443,542,1.985
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,101.049,3.424,104.473
12,13,Oli esauriti e residui di combustibili liquidi...,-,4.638,4.638
13,14,"Solventi organici, refrigeranti e propellenti ...",-,221,221
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",72.571,3.924,76.495
15,16,Rifiuti non specificati altrimenti nell'elenco,86.651,35.443,122.094
16,17,Rifiuti delle attività di costruzione e demoli...,1.461.062,8.773,1.469.835
17,18,Rifiuti prodotti dal settore sanitario e veter...,111,1.803,1.914
18,19,Rifiuti prodotti da impianti di gestione dei r...,579.431,83.512,662.943
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,34.160,218,34.378
20,Totale,Totale,2.840.177,161.090,3.001.267

36

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,256,-,256.000
1,02 missing,None,NaN,NaN
2,03 missing,None,NaN,NaN
3,04 missing,None,NaN,NaN
4,05 missing,None,NaN,NaN
...,...,...,...,...
92,"93 - Attività sportive, di intrattenimento e d...",54,13,67.000
93,94 missing,None,NaN,NaN
94,95 missing,None,NaN,NaN
95,96 - Altre attività di servizi per la persona,50,7,57.000
96,Totale,275.487,17.152,292.639

37

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",130,-,130.000
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",6.741,-,6.741
2,03,Rifiuti della lavorazione del legno e della pr...,397,-,397.000
3,04,Rifiuti della lavorazione di pelli e pellicce ...,76,-,76.000
4,05,"Rifiuti della raffinazione del petrolio, purif...",-,440,440.000
5,06,Rifiuti dei processi chimici inorganici,6,5.719,5.725
6,07,Rifiuti dei processi chimici organici,48,3,51.000
7,08,"Rifiuti della produzione, formulazione, fornit...",98,22,120.000
8,09,Rifiuti dell'industria fotografica,1,13,14.000
9,10,Rifiuti provenienti da processi termici,59.997,3.902,63.899
10,11,Rifiuti prodotti dal trattamento chimico super...,21,159,180.000
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,2.798,780,3.578
12,13,Oli esauriti e residui di combustibili liquidi...,-,461,461.000
13,14,"Solventi organici, refrigeranti e propellenti ...",-,12,12.000
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",7.520,251,7.771
15,16,Rifiuti non specificati altrimenti nell'elenco,6.528,4.143,10.671
16,17,Rifiuti delle attività di costruzione e demoli...,139.061,657,139.718
17,18,Rifiuti prodotti dal settore sanitario e veter...,6,428,434.000
18,19,Rifiuti prodotti da impianti di gestione dei r...,49.783,155,49.938
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,2.276,7,2.283
20,Totale,Totale,275.487,17.152,292.639

38

,Descrizione attività,RS NP (t),RS P (t),Totale (t)
0,01 - Coltivazioni agricole e produzione di pro...,24.470,1.648,26.118
1,02 - Silvicoltura ed utilizzo di aree forestali,45,2,47
2,03 - Pesca e acquacoltura,778,2,780
3,04 missing,None,NaN,NaN
4,05 - Estrazione di carbone (esclusa torba),54,-,54
...,...,...,...,...
93,94 - Attività di organizzazioni associative,156,50,206
94,95 - Riparazione di computer e di beni per uso...,348,67,415
95,96 - Altre attività di servizi per la persona,4.702,168,4.870
96,ND - Attività ISTAT non determinata,3.936,507,4.443
97,Totale,16.156.053,1.188.962,17.345.015

39

,Capitolo dell'Elenco,Descrizione,RS NP (t),RS P (t),Totale (t)
0,01,"Rifiuti derivanti da prospezione, estrazione d...",520.457,128,520.585
1,02,"Rifiuti prodotti da agricoltura, orticoltura, ...",336.058,89,336.147
2,03,Rifiuti della lavorazione del legno e della pr...,414.527,547,415.074
3,04,Rifiuti della lavorazione di pelli e pellicce ...,219.343,29,219.372
4,05,"Rifiuti della raffinazione del petrolio, purif...",95,3.131,3.226
5,06,Rifiuti dei processi chimici inorganici,24.576,21.404,45.980
6,07,Rifiuti dei processi chimici organici,67.054,147.166,214.220
7,08,"Rifiuti della produzione, formulazione, fornit...",91.553,19.035,110.588
8,09,Rifiuti dell'industria fotografica,262,1.653,1.915
9,10,Rifiuti provenienti da processi termici,991.968,77.704,1.069.672
10,11,Rifiuti prodotti dal trattamento chimico super...,21.218,60.227,81.445
11,12,Rifiuti prodotti dalla lavorazione e dal tratt...,849.506,78.847,928.353
12,13,Oli esauriti e residui di combustibili liquidi...,-,73.173,73.173
13,14,"Solventi organici, refrigeranti e propellenti ...",-,7.797,7.797
14,15,"Rifiuti di imballaggio. Assorbenti, stracci, m...",542.187,30.167,572.354
15,16,Rifiuti non specificati altrimenti nell'elenco,369.228,228.364,597.592
16,17,Rifiuti delle attività di costruzione e demoli...,6.960.331,131.810,7.092.141
17,18,Rifiuti prodotti dal settore sanitario e veter...,983,13.153,14.136
18,19,Rifiuti prodotti da impianti di gestione dei r...,4.492.073,292.106,4.784.179
19,20,Rifiuti urbani (rifiuti domestici e assimilabi...,250.698,1.925,252.623
20,ND,Attività ISTAT non determinata,3.936,507,4.443
21,Totale,Totale,16.156.053,1.188.962,17.345.015

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.